discord.bot-token=${DISCORD_BOT_TOKEN:}
quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.jdbc.url=${DB_JDBC_URL:}
%prod.quarkus.datasource.username=teamkillcounter
%prod.quarkus.datasource.password=${DB_PASSWORD:}
%prod.quarkus.datasource.devservices.enabled=false
%prod.quarkus.hibernate-orm.schema-management.strategy=validate
%dev.quarkus.datasource.devservices.enabled=true
%dev.quarkus.datasource.devservices.image-name=postgres:18
%dev.quarkus.datasource.devservices.db-name=teamkill
%dev.quarkus.datasource.devservices.username=tkc
%dev.quarkus.datasource.devservices.password=tkc
%dev.quarkus.hibernate-orm.schema-management.strategy=validate
%test.quarkus.datasource.devservices.enabled=true
quarkus.flyway.migrate-at-start=true
