discord.bot-token=${DISCORD_BOT_TOKEN:}
quarkus.datasource.db-kind=postgresql
quarkus.datasource.devservices.enabled=true
quarkus.datasource.devservices.image-name=postgres:18
quarkus.datasource.devservices.db-name=teamkill
quarkus.datasource.devservices.username=tkc
quarkus.datasource.devservices.password=tkc
# optional, falls du Seed-Daten willst:
# quarkus.hibernate-orm.sql-load-script=import.sql
